# Generated by Django 3.2.15 on 2022-08-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220818_2136'),
        ('recipes', '0002_initial'),
    ]

    operations = [
    ]
